version: "2.15.1"
services:
  api:
    image: sigesit-app
    container_name: sigesit-api
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: inirahasia
      DB_NAME: db_sigesit
      PORT: 5000
      SECRET_KEY: kepoyaanda
      CONFIG_SMTP_HOST: smtp.gmail.com
      CONFIG_SMTP_PORT: 587
      CONFIG_SENDER_NAME: "SiGesit <sigesit@gmail.com>"
      CONFIG_AUTH_EMAIL: sidik.testing@gmail.com
      CONFIG_AUTH_PASSWORD: sizqwpxgcoxufwap
      REDIS_URL: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: inirahasia
      GIN_MODE: release
    # volumes:
    #   - ./:/var/www
    depends_on:
      - db
      - redis
    ports:
      - 5000:5000
    networks:
      - sigesit-networks

  db:
    image: mysql
    container_name: mysql-server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: inirahasia
      MYSQL_DATABASE: db_sigesit
    volumes:
      - /home/asidikrdn/Documents/docker-volume/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - sigesit-networks

  myadmin:
    image: phpmyadmin
    container_name: myadmin
    restart: unless-stopped
    links:
      - db
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - sigesit-networks

  redis:
    image: redis/redis-stack
    container_name: redis-server
    restart: unless-stopped
    environment:
      REDIS_ARGS: "--requirepass inirahasia"
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - sigesit-networks

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx-server
  #   restart: unless-stopped
  #   ports:
  #     - 8000:80
  #   volumes:
  #     - ./:/var/www
  #     - ./docker-compose/nginx:/etc/nginx/conf.d/
  #   networks:
  #     - sigesit-networks

networks:
  sigesit-networks:
    driver: bridge
